### ISSUE TITLE
[1st 12PP] Epoxy Inserts

### ISSUE THREAD

**Issue by rocco8773** [rocco8773/gaps_work#20]

**Comment by rocco8773** [comment]
I (@rocco8773) put this task on pause since I noticed (on the 10PPs) that the torlon inserts were compressing the foam when fully tightened down.  This is due to the fact that the inserts are designed for a nominal thickness of 0.320" while the 10PPs have a nominal thickness of 0.376".  The Marketing Masters engineer said these inserts would work for a panel this thick.

The first solution to this is to only tighten the inserts until they just touch the face of the panel, and allow the epoxy for fill up the gap.  I'm not a big fan of this idea since we'd be relying on the compressive strengths of the epoxy.

**Comment by rocco8773** [comment]
> The first solution to this is to only tighten the inserts until they just touch the face of the panel, and allow the epoxy for fill up the gap. I'm not a big fan of this idea since we'd be relying on the compressive strengths of the epoxy.

Instead of relying on the compressive strengths of the epoxy, we can cut small washers (7/16" OD, 5/16" ID) out of 0.030" thick G10/FR4.  The will "resize" the inserts to work with of board of 0.350" nominal thickness.

I've tested this out and the concept works well.  The sleeve and plug of the insert still properly engage when tightened down.  To make the washers though, I have to punch them out of a sheet of 0.030" thick Garolite at home on my shop press (the Arbor press in the lab is not strong enough to punch.).

**Comment by rocco8773** [comment]
As of today, I have punched 37 G10/FR4 washers.  Of which,

- 4x are fully processed and ready for epoxying
- 33x need to have their final sanding to fit done

---

I have 3d printed a jig to help sand the washers to their final fit.



![Image](https://user-images.githubusercontent.com/29869348/194926050-98b02991-e441-48f3-825f-ee2222639157.png)

**Comment by rocco8773** [comment]
The spacer design is working well on the 1st 12PP.  Notes when epoxying:

1. Do NOT put the washer around the plug insert and then insert them together in the panel.  The washer tolerance is tight and will often catch on the edge of the panel when tightening the inser.
2. When placing the inserts (1) put the sleeve insert into the panel, (2) put the G10/FR4 washer into the panel using tweezers, (3) drop the plug insert into the panel, (4) tighten insert by hand but keep it at a light hand tight.

**Comment by rocco8773** [comment]
Inserts are fully potted into when end of the panel.  The opposite end has the flat inserts potted in.  

Currently we are one G10 washer short of being able to pot the remaining inserts.

**Comment by katieecallahann** [comment]
All inserts have been epoxied
