### ISSUE TITLE
Cutting 6cm and 10cm wire for circular connectors

### ISSUE THREAD

**Issue by Jackdickson89** [rocco8773/gaps_work#38]
Twice as many black wires as everything else, same as the other wire cutting. Use this task when you are in alone and have nothing else to do or you are looking for something as a break
- [ ] 180 each 6cm wires
- [ ] 180 each 10cm wire

**Comment by rocco8773** [comment]
@Jackdickson89 Is this the same as #27, or a subset of #27.

**Comment by rocco8773** [comment]
Closing in favor of #27
